#config .yml
<<<<<<< HEAD
# spring.application.name=hotelDemo
=======
# spring.application.name=HotelDemo
>>>>>>> fdd4c4c (first commit)
server:
  port: 8080

#config database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hoteldb
    username: root
    password: 123456n
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
<<<<<<< HEAD
    database-platform: org.hibernate.dialect.MySQLDialect
=======
>>>>>>> fdd4c4c (first commit)
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
