#config .yml
# spring.application.name=hotelDemo
<<<<<<< HEAD
# spring.application.name=HotelDemo
=======
>>>>>>> feature_nuong
server:
  port: 8080

#config database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hoteldb
    username: root
    password: 123456n
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  flyway:
    enabled: true
    locations: classpath:db/migration





